### ISSUE TITLE
User A calls User B, User A Decline call simultaneously User A Accepts Call the call not ended for User A.

### ISSUE THREAD

**Issue by sridharvthink** [voxeet/voxeet-sdk-ios#15]
**Describe the bug**
User A calls User B, User A Decline call simultaneously User A Accepts Call the call not ended for User A.

**Expected Behaviour**
It should End For User A

**Steps to Reproduce the Problem**

1. User A receives a call from user B
2. User A picks the call User B declines the call at the same time
3. however User A starts a new calling screen (Looks like call no ended)

**Specifications**
iOS 12 onwards Device: iPhone and iPad 
SDK Version: 1.4.7, 1.4.8

**Comment by VTCoco** [comment]
Thank you for the flow @sridharvthink, sorry for the delay I will check it after my sprint.

**Comment by VTCoco** [comment]
Hello @sridharvthink, this issue is patch with the last 2.0.0 release (https://github.com/voxeet/voxeet-sdk-ios/releases/tag/v2.0.0).
