### ISSUE TITLE
Screen share not happening with SDK

### ISSUE THREAD

**Issue by srinivasdr** [voxeet/voxeet-sdk-ios#17]
**Describe the bug**

Voxeet screen share is showing red screen in the simulator who joined as participant when we call  VoxeetSDK.shared.conference.startScreenShare  method  from host app running in  device

**Expected Behaviour**
It should show actual screen which is being recorded in simulator

**Steps to Reproduce the Problem**

  1. Go and install  sample app in device
  2. Install same sample app in simulator
  3. create and join conference in iPad device
  4. call VoxeetSDK.shared.conference.startScreenShare  from device after joining conference
  5. We see red screen in simulator who as joined same conference with conference id of device joined conference
 6. Different delegate methods are called like streamAdded and screenShareView.attach(participant: participant, stream: stream)  is executed
7. But still in simulator only red screen is shown

**Minimalistic code (recommended)**

@IBAction func startScreenShare(_ button: UIButton) {
        if #available(iOS 11.0, *) {
            if button.isSelected {
                guard VoxeetSDK.shared.mediaDevice.screenShareMediaStream() == nil else {
                    // Debug.
                    print("[Sample] \(String(describing: ConferenceViewController.self)).\(#function).\(#line) - Error: Only one screen share allowed.")
                    return
                }
                
                button.isEnabled = false
                VoxeetSDK.shared.conference.startScreenShare { (error) in
                    
                }
                
            } else {
                button.isEnabled = false
                VoxeetSDK.shared.conference.stopScreenShare(completion: { error in
                    DispatchQueue.main.async {
                        button.isEnabled = true
                        
                        if let error = error {
                            // Debug.
                            print("[Sample] \(String(describing: ConferenceViewController.self)).\(#function).\(#line) - Error: \(error)")
                        } else {
                            button.isSelected = true
                            button.setTitle("Start screen share", for: .normal)
                        }
                    }
                })
            }
        }
    }

func streamAdded(participant: VTParticipant, stream: MediaStream) {
        switch stream.type {
        case .Camera:
            if participant.id == VoxeetSDK.shared.session.participant?.id {
                // Attaching own participant's video stream to the renderer.
                if !stream.videoTracks.isEmpty {
                    ownCameraView.attach(participant: participant, stream: stream)
                    ownCameraView.isHidden = false
                }
            } else {
                tableView.reloadData()
            }
        case .ScreenShare:
            // Attaching a video stream to a renderer.
            screenShareView.attach(participant: participant, stream: stream)
            screenShareView.alpha = 1
        default:
            break
        }
    }

[Please provide a link to a repository showing specifically the issue. It should only have the minimal footprint of your own implementation - something which does not requires any NDA.]

**Specifications**

  - Device: iPad
  - OS: 13
  - Platform: iOS
  - Subsystem: [
  - Version: SDK 2.0
  - Using trial version

**Comment by VTCoco** [comment]
Hello @srinivasdr, thank you for your feedback.
Unfortunately the simulator can't sent/received a video stream properly (video or screen share), you need to use two real devices to have this feature working properly.

**Comment by srinivasdr** [comment]
Thanks @VTCoco 
Does the screen sharing works from iPad device to web browser app?

**Comment by VTCoco** [comment]
Yes :)

**Comment by srinivasdr** [comment]
Ok thank you !

**Comment by VTCoco** [comment]
With the VoxeetSDK v2.2.1 the screen share only works inapp, if you go to the homescreen it will be stopped.
We should release the v2.3.0 next week to improve the screen share to stream inapp **AND** homescreen etc. With this new version you will see the recording symbol on top of the iPad.

**Comment by VTCoco** [comment]
Screen share documentation: https://dolby.io/developers/interactivity-apis/client-sdk/articles/screenshare-with-ios#implementation-guide
