### ISSUE TITLE
Screen broadcast does not work with UIScene lifecycle (Xcode 11's default)

### ISSUE THREAD

**Issue by cardoso** [voxeet/voxeet-sdk-ios#18]
When calling startScreenShare(broadcast:true), nothing shows up, stream remains black, and the callback comes back with this error:

```
Error Domain=com.voxeet.sdk Code=-2343 "Broadcast picker displayed." UserInfo={NSLocalizedDescription=Broadcast picker displayed.}
```

And this shows up in the logs afterwards:
```
[Assert] Error in UIKit client: -[UIWindow setScreen:] should not be called if the client adopts UIScene lifecycle. Call -[UIWindow setWindowScene:] instead.
```

A workaround is to [adopt the old lifecycle](https://stackoverflow.com/questions/57467003/xcode-11-opt-out-of-uiscenedelegate-swiftui-on-ios-13), but it's definitely not ideal going forward. It would be better if the SDK could detect the new lifecycle and adopt new methods instead.

**Comment by VTCoco** [comment]
Hello,

I don't think we could fix this for the moment because this error comes from ReplayKit.framework.

http://openradar.appspot.com/FB7671583

I'm afraid that the solution (for now) is to wait a fix from Apple.

**Comment by cardoso** [comment]
Thanks @VTCoco . That makes sense.

**Comment by mohadel92** [comment]
> When calling startScreenShare(broadcast:true), nothing shows up, stream remains black, and the callback comes back with this error:
> 
> ```
> Error Domain=com.voxeet.sdk Code=-2343 "Broadcast picker displayed." UserInfo={NSLocalizedDescription=Broadcast picker displayed.}
> ```
> 
> And this shows up in the logs afterwards:
> 
> ```
> [Assert] Error in UIKit client: -[UIWindow setScreen:] should not be called if the client adopts UIScene lifecycle. Call -[UIWindow setWindowScene:] instead.
> ```
> 
> A workaround is to [adopt the old lifecycle](https://stackoverflow.com/questions/57467003/xcode-11-opt-out-of-uiscenedelegate-swiftui-on-ios-13), but it's definitely not ideal going forward. It would be better if the SDK could detect the new lifecycle and adopt new methods instead.

any further details regarding this issue , i was going to implement share screen sdk?

**Comment by FabienLavocat** [comment]
Closing this issue, if this still happens, please reopen.
