### ISSUE TITLE
Use of deprecated swift API UILocalNotification (XCode 11.5)

### ISSUE THREAD

**Issue by asim-najam** [voxeet/voxeet-sdk-ios#19]
**Describe the bug**
I install Voxeet using cocoa `pod 'VoxeetUXKit', '~> 1.0'`
When I import the following: 
- import VoxeetSDK
- import VoxeetUXKit

XCode gives an error: 

File: VoxeetSDK-swift.h
'UILocalNotification' is deprecated: first deprecated in iOS 10.0 - Use UserNotifications Framework's UNNotificationRequest

**Expected Behaviour**
Project should compile with no error.

**Steps to Reproduce the Problem**

  1. install library using `pod 'VoxeetUXKit', '~> 1.0'`
  2. `import VoxeetSDK` and `import VoxeetUXKit` on AppDelegate 
  3. Build the project

**Specifications**

  - OS: iOS 11.0
  - Platform: iOS
  - Swift Version: 5.2.4

  - Version:
    - VoxeetSDK (2.3.1) and VoxeetUXKit (1.3.4)

**Comment by vjard** [comment]
Hello @asim-najam,

Thank you for your feedback.
Is it a warning or an error ? 
I can see this warning with Swift 4.2 project but cannot see with Swift 5.
We support the latest version of swift (Swift 5 in build settings).

**Comment by asim-najam** [comment]
@vjard apology but my swift version is 4.2. It's an error.

**Comment by vjard** [comment]
<img width="1788" alt="Screenshot Xcode" src="https://user-images.githubusercontent.com/60706851/84403363-e67d3280-ac05-11ea-8661-4fb91db1dd61.png">
@asim-najam Is it the same warning ?

**Comment by asim-najam** [comment]
<img width="1391" alt="Screenshot 2020-06-11 at 8 20 27 PM" src="https://user-images.githubusercontent.com/3080513/84405045-0cfc9700-ac21-11ea-85f0-289f32f35a43.png">
@vjard Yes it is the same, but for me it is showing as an error.

**Comment by asim-najam** [comment]
@vjard Apologies! my bad, in my project `Treat warning as error` was turned `On`. That's why i'm getting this as an error. Any ways thank you for your help and quick response. I appreciate it 👍

**Comment by asim-najam** [comment]
@vjard Could you please help me with this issue.
Swift `Compiler -> Treat warning as error` is turned to `Yes`
In Pod file:

`use_frameworks!`
`inhibit_all_warnings!`
But when I import `VoxeetSDK`
Compile failed with error: `could not build Objective-C module 'VoxeetSDK'`
Any help from you would be appreciated.

**Comment by VTCoco** [comment]
Your last question isn't related to the main subject of this ticket, could you open a new one if you still have a question please?

_However I'm not sure it's a good idea to enable `Treat warning as error`._
