### ISSUE TITLE
Update Voxeet SDK to support Xcode 12/Swift 5.3

### ISSUE THREAD

**Issue by fivenorth** [voxeet/voxeet-sdk-ios#20]
Failed to build module 'VoxeetSDK' from its module interface; the compiler that produced it, 'Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3 (swiftlang-1200.0.16.13 clang-1200.0.22.25)'

**Comment by VTCoco** [comment]
Hello,
Are you using Xcode 12 beta 3? (https://developer.apple.com/download)
Are your building dependencies Carthage?

**Comment by fivenorth** [comment]
Hello,

Using Xcode Beta 3 and CocoaPods. 

Best ~ Scott

**Comment by VTCoco** [comment]
Ok, can you try to download it manually and test it without Carthage or CocoaPods please? The SDK should be retro compatible but those dependencies managers can block a framework that have a precise Swift version.

https://vox-ios-sdk.s3.us-east-1.amazonaws.com/sdk/ios/release/2.4.0/VoxeetSDK.zip

**Comment by fivenorth** [comment]
Adding it manually does workaround the problem. Thanks.

**Comment by Hubtwork** [comment]
i've manually download that sdk and add voxeetsdk , webrtc to framwork directory in my project manually.

but same issue opened.can you explain some work flow with steps ? I'm newb in these works. sorry

**Comment by VTCoco** [comment]
I think I got the same issue with Xcode 12 beta 6 even by adding it manually, @fivenorth what was your beta version of Xcode 12? This new beta might break something related to the SDK module interface.

```
Showing Recent Messages
/Users/clarr/Projects/production/voxeet-ios-sdk/Sample/VoxeetSDK Sample/ViewController.swift:10:8: Failed to build module 'VoxeetSDK' from its module interface; the compiler that produced it, 'Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3 (swiftlang-1200.0.28.1 clang-1200.0.30.1)'
```

**Comment by Hubtwork** [comment]
Yeah ... 
I think xcode12 beta 6 has also same issue for swift module stability ... so just release repackaging on swift 5.3 needed plz...

**Comment by vjard** [comment]
Hello @fivenorth , @Hubtwork , can you try this Voxeet SDK built with Xcode 12 : 
https://dolby.box.com/s/ouo75dp7nu2khdg1um0lmocm7w8szo2c

**Comment by vjard** [comment]
For those who would like to try this beta on a simulator, we currently cannot. There is an Xcode bug on frameworks that does not allow you to generate a device + simulator compatible framework, here is the thread that talks about it: https://developer.apple.com/forums/thread/657913

This beta is only compatible for devices, not simulator.

**Comment by fivenorth** [comment]
Hi @vjard . I'm pretty sure this isn't an Xcode bug. It's been an extra step for frameworks vendors since at least Xcode 11 as demonstrated here: https://devforum.zoom.us/t/ios-sdk-building-for-ios-simulator-but-the-linked-and-embedded-framework-mobilertc-framework-was-built-for-ios/12171. Basically you need to provide simulator support as part of the SDK distribution. This seems like a pretty time-sensitive issue for those using your platform (like my company) considering Xcode 12 just GM'd today. :) Can you give us an update as when we expect to have this resolved?

**Comment by VTCoco** [comment]
Useful ticket: https://developer.apple.com/forums/thread/657913
arm64 will be used for future simulators with silicon arm MacBooks, **but** it has already been implement in the Xcode 12.

We are trying to find a workaround.

**Comment by VTCoco** [comment]
The 2.4.1 is available here: https://github.com/voxeet/voxeet-sdk-ios/releases/tag/v2.4.1

**CHANGELOG:** Convert for Swift 5.3 and Xcode 12 compatibility (support for the **simulator** & **CocoaPods** has been temporarily removed).

**Comment by VTCoco** [comment]
We are working to support the simulator again in a future release (== CocoaPods support too).
For now you can update it with **Carthage** or by downloading it manually at https://vox-ios-sdk.s3.us-east-1.amazonaws.com/sdk/ios/release/2.4.1/VoxeetSDK.zip.
