### ISSUE TITLE
Request for compiling package based on swift 5.3

### ISSUE THREAD

**Issue by Hubtwork** [voxeet/voxeet-sdk-ios#21]
Apple launched new osx big sur beta and new xcode 12 beta which has swift 5.3 compiler.

In new development environment with enhanced swiftUI is very attractive, but importing Voxeetsdk is unavailable because of compiled swift version.

So request for recompiled version on swift 5.3

**Comment by VTCoco** [comment]
Hello, for now use this trick please: https://github.com/voxeet/voxeet-sdk-ios/issues/20
The issue is coming from CocoaPods / Carthage dependencies managers.
