### ISSUE TITLE
Voxeet SDK - For iOS 14

### ISSUE THREAD

**Issue by w3b-amit** [voxeet/voxeet-sdk-ios#22]
We want to make our app ready for iOS 14 which is using Voxeet SDK for Calling feature. So can we get an SDK compatible with iOS 14 or some date till when we are getting the update for this new iOS?
Thank you.

**Comment by Hubtwork** [comment]
I already requested release feature based on Swift 5.3 compiler to dolby.io and they reply me that they will.

So if it released, ios14 compatibility will be totally solved.

**Comment by vjard** [comment]
Hello @w3b-amit, @Hubtwork .
This is a duplicated post, I close this one, go on https://github.com/voxeet/voxeet-sdk-ios/issues/20
Thank you !
