### ISSUE TITLE
「3D Audio」is doesn't work?

### ISSUE THREAD

**Issue by kosukekurimoto** [voxeet/voxeet-sdk-ios#24]
I tested 3D Audio using two iPhones.
But unfortunately there was no conversion to audio.

![120109289_1191924971169427_8654158764825026919_n](https://user-images.githubusercontent.com/27758476/94234096-f36b2b00-ff43-11ea-90d5-b0ce95e29671.jpg)

<img width="1189" alt="スクリーンショット 2020-09-25 15 26 22" src="https://user-images.githubusercontent.com/27758476/94234109-fa923900-ff43-11ea-984f-d8729b3bf687.png">

**Comment by VTCoco** [comment]
Because this type of question is internal to SDK please contact support located into your Voxeet dashboard, thank you.

**Comment by kosukekurimoto** [comment]
Thank you very much. I will contact support.

**Comment by VTCoco** [comment]
With v3.x 3D audio isn't supported anymore. It has been replaced by Dolby Voice.
