### ISSUE TITLE
Stop unwanted debug logs in version 3.0.0

### ISSUE THREAD

**Issue by w3b-amit** [voxeet/voxeet-sdk-ios#26]
Hi team, 
We are getting lots of log in debug console after updating Voxeet SDK to version 3.0.0 and this issue is in both iOS and android SDK.
Is there any way to prevent these logs. It will be very helpful for us. 
Thank you

**Comment by FabienLavocat** [comment]
Hi @w3b-amit we are aware of this. The logs come from one of the dependency and we are working on reducing the amount of logs coming to the console. I'll keep you posted when I have more information about an update.

**Comment by VTCoco** [comment]
https://github.com/voxeet/voxeet-sdk-ios/releases/tag/v3.0.1 should fix this ticket.
