### ISSUE TITLE
Failed to compile project on Bitrise

### ISSUE THREAD

**Issue by astrokin** [voxeet/voxeet-sdk-ios#28]
Locally everything works fine, but on an Bitrise I'm not able to archive the project. Cold you please help? Did someone faced with this problem?

**Comment by VTCoco** [comment]
Hello, do you have anything that can help us to determine what is the cause of it?
SDK version?
Was it working before a specific SDK version?

**Comment by astrokin** [comment]
Issue were resolved by changing Xcode version
