### ISSUE TITLE
v3.1.0-beta.2 - Frameworks

### ISSUE THREAD

**Issue by w3b-amit** [voxeet/voxeet-sdk-ios#29]
I have implemented Voxeet SDK manually in my project instead of Pods, So I want a compiled framework for the Voxeet SDK - v3.1.0-beta.2 as we have for other vesions over here - https://raw.githubusercontent.com/voxeet/voxeet-sdk-ios/master/VoxeetSDK.json. Please provide us the framework files for this version.

**Comment by VTCoco** [comment]
Hello,

You just have to select the https://github.com/voxeet/voxeet-sdk-ios/tree/v3.1.0-beta.2 branch, open the VoxeetSDK.json and see the link available here: https://vox-ios-sdk.s3.us-east-1.amazonaws.com/sdk/ios/release/v3.1.0-beta.2/VoxeetSDK.zip

**Comment by VTCoco** [comment]
Don't forget if you aren't using cocoapods or carthage, you will have to remove simulator architecture in order to compile your project with lipo command.

**Comment by w3b-amit** [comment]
Thank you.
I would like to know the CocoaPod target for voxeet SDK. Please let me know.

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
22/02/21,
02:19:00 pm

**Comment by VTCoco** [comment]
It should be: `pod 'VoxeetSDK', :git => 'https://github.com/voxeet/voxeet-sdk-ios', :branch => 'v3.1.0-beta.2'
`

**Comment by w3b-amit** [comment]
Thank you.

**Comment by w3b-amit** [comment]
HI @VTCoco, After installing SDK with pod it is showing error at:
 @import VoxeetSDK;
ERROR: Module 'VoxeetSDK' not found

Please guide me to use VoxeetSDK with pod. I have installed the voxeet POD successfully.

**Comment by VTCoco** [comment]
My bad, my copy past was wrong. Instead of `pod 'VoxeetSDK', :git => 'https://github.com/voxeet/voxeet-sdk-ios', :branch => 'v3.1.0-beta.2'` please use `pod 'VoxeetSDK', '3.1.0-beta.2'`.

**Comment by VTCoco** [comment]
Are you using the UXKit alongside the SDK or only the SDK standalone? _(the UXKit will need an update in order to be compatible with v3.1.0-beta.2)_

**Comment by w3b-amit** [comment]
I am using Voxeet SDK standalone.

**Comment by w3b-amit** [comment]
Hi @VTCoco,
I am facing an issue while uploading the app for test flight when I use - V3.1.0-beta.2 SDK version. Please look into the issue. 
I am attaching a screenshot of the issue which comes while uploading.
<img width="1427" alt="Screenshot 2021-02-23 at 6 34 45 PM" src="https://user-images.githubusercontent.com/28981682/108847519-cf506a80-7605-11eb-975c-c26142bbc394.png">

**Comment by VTCoco** [comment]
Hello, is "Show Logs" have something more explicit @w3b-amit?

**Comment by VTCoco** [comment]
Closing this ticket due to inactivity, @w3b-amit if this ticket is still relevant please reopen it.
