### ISSUE TITLE
VoxeetSDK crashes the debugger

### ISSUE THREAD

**Issue by yasserosama07** [voxeet/voxeet-sdk-ios#30]
**Describe the bug**

Run the sample app, add breakpoint anywhere, when using "po or p" i get 
error: virtual filesystem overlay file '/Users/voxeet/Library/Developer/Xcode/DerivedData/VoxeetSDK-ftomkwuqrnfvtreyrfoxdtigyjhn/Build/Intermediates.noindex/ArchiveIntermediates/VoxeetSDK/IntermediateBuildFilesPath/VoxeetSDK.build/Release-iphoneos/VoxeetSDK.build/all-product-headers.yaml' not found

error: couldn't IRGen expression. Please check the above error messages for possible root causes.

and i get the same error trying " po " while debugging on different project with VoxeetSDK installed 

**Expected Behaviour**

the debugger prints out the value

**Steps to Reproduce the Problem**

  - add breakpoint on logInButtonAction
  - press login button
  - in the debugger write "po sessionTextField.text"
  
![image](https://user-images.githubusercontent.com/26869176/111304255-3047ed00-865e-11eb-895d-38bdc75d8d74.png)

**Minimalistic code (recommended)**

https://github.com/voxeet/voxeet-sdk-ios-gettingstarted

**Specifications**

  - Device: iPhone 11 ( Real device ) & iPhone 8 ( Simulator )
  - OS: 14.4
  - Platform: iOS
  - Version:
    -[VoxeetSDK] 3.1.1

**Comment by FabienLavocat** [comment]
Thank you for reporting this @yasserosama07, I'll get back to you with an answer.

**Comment by vjard** [comment]
Hello @yasserosama07,
  @VTCoco and me have worked on this. Should be fix on the next release 3.1.2 (will be available in the next few days/week).

**Comment by FabienLavocat** [comment]
Hi @yasserosama07, we have release our SDK 3.1.2 for iOS - https://github.com/voxeet/voxeet-sdk-ios/blob/master/CHANGELOG.md#v312 - it contains the fix for the p / po command issue you were facing.

![Screen Shot 2021-03-25 at 2 24 01 PM](https://user-images.githubusercontent.com/4154532/112545887-f8cff380-8d75-11eb-8c58-66acc2a64d89.png)

Thanks for reporting it!
