### ISSUE TITLE
Unable to compile application for iOS simulator running on Intel using Xcode 12.5/Swift 5.4

### ISSUE THREAD

**Issue by fivenorth** [voxeet/voxeet-sdk-ios#32]
A sampling of errors:

![Image 2021-04-26 at 5 47 32 PM](https://user-images.githubusercontent.com/53768/116168551-837a7a00-a6b7-11eb-8f2c-a5ba1e01750f.jpg)

**Comment by FabienLavocat** [comment]
Hi @fivenorth! What version of the SDK are you trying to use?
@VTCoco Could you please have a look?

**Comment by fivenorth** [comment]
Hi Fabien!

I’ve tried with both 3.1.3 and 3.1.4.

Best ~ Scott

**Comment by VTCoco** [comment]
An update of the SDK will be provided today in order to Support Xcode 12.5 and the new Swift version.

**Comment by VTCoco** [comment]
Release available to support Xcode 12.5 and Swift 5.4 @fivenorth: https://github.com/voxeet/voxeet-sdk-ios/releases/tag/v3.1.5
