### ISSUE TITLE
iOS device can't call some android device

### ISSUE THREAD

**Issue by CHNDarryl** [voxeet/voxeet-sdk-ios#33]
Hi:
We have a problem, on some Android devices, if iOS creates the meeting first(createWithOptions:), joins the meeting(joinWithConference:). Then Android joins the meeting. Android will leave the meeting immediately.

**Comment by FabienLavocat** [comment]
Hi,
One possible issue is the Codec used. iOS will by default create a conference using the H264 codec. This codec is not supported on all Android devices. Try to force the VP8 codec when you create the conference and try the same scenario again.

Thanks,
Fabien

**Comment by CHNDarryl** [comment]
Ok,Thank you.I try it,It's works!
