### ISSUE TITLE
Deinitialiaze VoxeetSDK

### ISSUE THREAD

**Issue by vodemn** [voxeet/voxeet-sdk-ios#65]
VoxeetSDK has the `initialize` method, but is there a way to deinitialize it?
For example, when user logs out from the application we don't want to receive invitation events, but we do.

**Comment by FabienLavocat** [comment]
Hi @vodemn,
If you want your end users to not receive invitation events, you can close the session.
See: https://docs.dolby.io/communications-apis/docs/ios-client-sdk-sessionservice#close

**Comment by vodemn** [comment]
Thanks @FabienLavocat !
And will I be able to then initialize SDK with different token?

**Comment by FabienLavocat** [comment]
You can re-initialize the SDK with a different token yes, but you do not need to since the token is not linked to a user.
