### ISSUE TITLE
is there any ios screen sharing sample project using voxeet-sdk ?

### ISSUE THREAD

**Issue by mohd-afid** [voxeet/voxeet-sdk-ios#66]

**Comment by WingofaGriffin** [comment]
Hi @mohd-afid. We have a getting started guide to use the screen sharing feature you can find here: https://docs.dolby.io/communications-apis/docs/implement-screen-sharing-for-ios

We also have a sample app for this you can find here: https://github.com/dolbyio-samples/comms-sdk-ios-getting-started

Let me know if that is what you're looking for, or if you are looking for something different.

**Comment by mohd-afid** [comment]
@WingofaGriffin i am using flutter to develop screen sharing app. above shown sample project isn't  flutter.

**Comment by codlab** [comment]
You actually did open a ticket in the native sdk repository. Regarding flutter you can have more information going into https://github.com/DolbyIO/comms-sdk-flutter ; specifically you can see in its internal test app the mechanism regarding starting screen share sessions:

https://github.com/DolbyIO/comms-sdk-flutter/blob/1e05c1b9b4d06743b5a6dd2ca71a3b25fed6883b/test_app/lib/screens/participant_screen/conference_controls.dart#L170

**Comment by mohd-afid** [comment]
https://github.com/DolbyIO/comms-sdk-flutter/blob/1e05c1b9b4d06743b5a6dd2ca71a3b25fed6883b/test_app/lib/screens/participant_screen/conference_controls.dart#L170
this sample project screen share is not working ios  because this project not using any broadcast extension. currently my project is screen share possible only on android . in ios In-App screen recording: Publishes the contents of your app only are 
working .
Broadcast Extension screen recording: Publishes the contents of your screen, on any app - this is not working  . currently i am stuck in there
https://github.com/flutter-webrtc/flutter-webrtc/wiki/iOS-Screen-Sharing. i am following this wiki
