### ISSUE TITLE
Is there a way to determine which participants are currently speaking?

### ISSUE THREAD

**Issue by vodemn** [voxeet/voxeet-sdk-ios#67]
My intent is to determine what users are currently speaking and indicate it to the local user. Is there a way to implement it?

**Comment by j12y** [comment]
The `isSpeaking()` method returns the current status for a participant if they are speaking or not. 

https://docs.dolby.io/communications-apis/docs/ios-client-sdk-conferenceservice#isspeaking

Let me see if I can find any sample code from a project.
