### ISSUE TITLE
activeParticipants feature is missing from latest release

### ISSUE THREAD

**Issue by dzeitman** [voxeet/voxeet-sdk-ios#68]
SDK Version [VoxeetSDK] 3.8.0 (1) 

delegate function  activeParticipants is never called.
Appears not part of the latest SDK that is pulled from Main on this repo;  Attempted to go to definition in Xcode - function not found. 

Example Usage:
```
extension ViewController: VTConferenceDelegate {

// ... other delegate functions

 func activeParticipants(notification: VTActiveParticipantsNotification){
        let participants = notification.participants;
        participants.forEach { participant in            
            if participant.id == VoxeetSDK.shared.session.participant?.id {
                localParticpant = participant;
                print(participant.info.name as Any);
            }else {
                // remote
                remoteParticpant = participant;
                print(participant.info.name as Any);
            }
            
        }
    }

/// end of code
}
```

Documentation suggest this feature should be included in the latest release: 
https://docs.dolby.io/communications-apis/docs/ios-client-sdk-conferenceservice

participantAdded

▸ participantAdded(participant: [VTParticipant](https://docs.dolby.io/communications-apis/docs/ios-client-sdk-model-vtparticipant))

Emitted when a new participant is invited to a conference. The SDK does not emit the participantAdded event for the local participant. Listeners only receive the participantAdded events about users; they do not receive events for other listeners. In SDK 3.2 and prior releases, users receive events about users and the first 1000 listeners **. However, in SDK 3.3 and next releases, users receive the participantAdded events about users and do not receive any events about listeners. To notify all application users about the number of participants who are present at a conference, the iOS SDK 3.3 introduces the [activeParticipants](https://docs.dolby.io/communications-apis/docs/ios-client-sdk-notificationservice#activeparticipants) events.**

**Comment by FabienLavocat** [comment]
You need to explicitly subscribe to this event: https://docs.dolby.io/communications-apis/docs/ios-client-sdk-notificationservice#subscribe

**Comment by dzeitman** [comment]
Documentation tripped me up on this...  

- First the assumption is activeParticpants was just a new delegate since its functionality is core to the ConferenceService 
- The hyperlink brought me to the middle of the document -- I didn't scroll up to see that the method was part the NotificationService --  Perhaps we can improve this by including which api delegate an method belongs to with the other information about the method.  
- Finally this method delegate seems misplaced;  notifications has a very different context on iOS -- I didn't actually expect the activeParticpants delegate method to be part of NotificationsService API.


Suggest that the updated doc for the callout of the changes should read more precisely:

Emitted when a new participant is invited to a conference. The SDK does not emit the participantAdded event for the local participant. Listeners only receive the participantAdded events about users; they do not receive events for other listeners. In SDK 3.2 and prior releases, users receive events about users and the first 1000 listeners. However, in SDK 3.3 and next releases, users receive the participantAdded events about users and do not receive any events about listeners. To notify all application users about the number of participants who are present at a conference, the iOS SDK 3.3 introduces the [activeParticipants](https://docs.dolby.io/communications-apis/docs/ios-client-sdk-notificationservice#activeparticipants) events **as part of the Notification Service**.

**Comment by FabienLavocat** [comment]
It is possible to get the activeParticipants outside of the conference so it does not belong to the ConferenceService.
@dzfill Could you please have a look at this suggestion?

**Comment by dzfill** [comment]
@FabienLavocat I am closing this issue, seeing as activeParticipants is not described at all in the ConferenceService, and the link goes to the notification service page.
